version: "3.8"

services:
    # Fedora development container
    fedora:
        build:
            context: ..
            dockerfile: container/Dockerfile.fedora
            args:
                USER_UID: ${USER_UID:-1000}
                USER_GID: ${USER_GID:-1000}
        container_name: my-unicorn-fedora
        hostname: fedora-dev
        restart: unless-stopped
        volumes:
            # Persistent .config directory (isolated from host)
            - my-unicorn-fedora-config:/home/devuser/.config
        working_dir: /home/devuser/my-unicorn
        environment:
            - DISTRO=fedora
            - XDG_CONFIG_HOME=/home/devuser/.config
        tty: true
        stdin_open: true

    # Arch Linux development container
    arch:
        build:
            context: ..
            dockerfile: container/Dockerfile.arch
            args:
                USER_UID: ${USER_UID:-1000}
                USER_GID: ${USER_GID:-1000}
        container_name: my-unicorn-arch
        hostname: arch-dev
        restart: unless-stopped
        volumes:
            # Persistent .config directory (isolated from host)
            - my-unicorn-arch-config:/home/devuser/.config
        working_dir: /home/devuser/my-unicorn
        environment:
            - DISTRO=arch
            - XDG_CONFIG_HOME=/home/devuser/.config
        tty: true
        stdin_open: true

    # Debian development container
    debian:
        build:
            context: ..
            dockerfile: container/Dockerfile.debian
            args:
                USER_UID: ${USER_UID:-1000}
                USER_GID: ${USER_GID:-1000}
        container_name: my-unicorn-debian
        hostname: debian-dev
        restart: unless-stopped
        volumes:
            # Persistent .config directory (isolated from host)
            - my-unicorn-debian-config:/home/devuser/.config
        working_dir: /home/devuser/my-unicorn
        environment:
            - DISTRO=debian
            - XDG_CONFIG_HOME=/home/devuser/.config
        tty: true
        stdin_open: true

# Named volumes for persistent .config directories (isolated per distro)
volumes:
    my-unicorn-fedora-config:
        driver: local
    my-unicorn-arch-config:
        driver: local
    my-unicorn-debian-config:
        driver: local
